In [1]:
# 导入mnist
from keras.datasets import mnist

# 拆分训练集和测试集
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()


Using TensorFlow backend.


# 接下来查看数据，数据格式均为numpy：

In [2]:
type(train_images)

numpy.ndarray

# 查看训练数据

In [3]:
train_images.shape

(60000, 28, 28)

In [4]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

# 查看测试数据

In [5]:
test_images.shape

(10000, 28, 28)

In [6]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

# 预处理

In [ ]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype('float32') / 255

# 搭建网络

In [7]:
# 导入模型和层
from keras import models
from keras import layers

In [8]:
# 搭建网路
network = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(28 * 28,)))
network.add(layers.Dense(10, activation='softmax'))

# 编译网络

In [10]:
network.compile(optimizer="rmsprop", loss='categorical_crossentropy', metrics=['accuracy'])
network.compile(optimizer="rmsprop", loss='categorical_crossentropy', metrics=['accuracy'])

[<tf.Variable 'dense_1/kernel:0' shape=(784, 512) dtype=float32, numpy=
 array([[-0.02509478,  0.06782787,  0.06037633, ..., -0.008842  ,
          0.01289106,  0.04711328],
        [ 0.04193198, -0.0181943 , -0.05370896, ..., -0.0306134 ,
         -0.03464412,  0.04029357],
        [ 0.05249489, -0.04311216,  0.05959332, ...,  0.02340676,
         -0.00827042,  0.05920529],
        ...,
        [ 0.05809134,  0.0364603 , -0.04105335, ..., -0.0401681 ,
          0.04345869,  0.06677395],
        [-0.06355197,  0.02657391, -0.06698032, ...,  0.03764617,
          0.00555876,  0.04420828],
        [-0.02165031, -0.00620116,  0.0248602 , ..., -0.03229707,
         -0.02884634, -0.02088729]], dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(512,) dtype=float32, numpy=
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,